### PR TITLE
add username and address

### PR DESCRIPTION
**Pull request by hKedia**

### CODE REVIEW

**Review by maxlibin — APPROVED** [review]
Thank you, we will send you 5 ada soon, please spread this around.

**Comment by maxlibin** [comment]
Thank you, we have sent you 5 ada on: https://explorer.cardano.org/en/address.html?address=addr1qxmpkhxydl4d5dumlgejqdthjhpa0n70579sk4skjulu2q8zjfr2sp8uyu675haf2ytq6658dyetkfr8fsc2c602h7hshg7ll0

again please share this around.

**Comment by hKedia** [comment]
Thanks, @maxlibin, good luck with the project. Will do 👍

**Comment by Davidminbank** [comment]
thanks

**Comment by Davidminbank** [comment]
thanks

**Pull request merged**
