### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by Plamen5kov**

### CODE REVIEW

**Comment by Plamen5kov** [comment]
yes, i did

**Comment by maxlibin** [comment]
> yes, i did

Which email do you use to register? can't find your email in our database.

**Comment by Plamen5kov** [comment]
i think it was plamen.krasimirov.petkov@gmail.com

**Comment by maxlibin** [comment]
Right, got it, we will send you 5 ada soon

**Comment by maxlibin** [comment]
Thanks, we have sent you 5 ADA: https://explorer.cardano.org/en/address.html?address=addr1qygepe5dvv9nf02qlrf55tjwa0lwkv6jzwejrrtrrkkj8kju52d6mj205ge44gd4f75g4fk9r09qny5rtgwmz0hrvwwsnlnvdt

**Pull request merged**
